### ISSUE TITLE
NIOCore.SocketAddressError.unknown(host: "::", port: 8080)

### ISSUE THREAD

**Issue by etrever** [VernissageApp/VernissageServer#146]
Trouble getting the api server running via docker compose.  

````
  vernissage-api:
    image: mczachurski/vernissage-server:develop
    hostname: vernissage-api
    container_name: vernissage-api
    restart: always
    expose:
      - 8080
    env_file: stack.env
    environment:
      TZ: Canada/Mountain
    volumes:
      - "/volume1/docker/my.domain.here/public/:/app/Public"
      - "/volume1/docker/my.domain.here/temp:/app/Temp"
````
stack.env has this
````
PG_USER=vernissage
PG_PASS=vernissage-db-password
PG_DB=vernissage
POSTGRES_PASSWORD=vernissage-db-admin-password
VERNISSAGE_BASEADDRESS="https://my.domain.here"
VERNISSAGE_CONNECTIONSTRING="postgres://$PG_USER:$PG_PASS@vernissage-db:5432/$PG_DB"
VERNISSAGE_QUEUEURL="redis://vernissage-redis:6379"
VERNISSAGE_S3ADDRESS=
VERNISSAGE_S3BUCKET=
VERNISSAGE_S3ACCESSKEYID=
VERNISSAGE_S3SECRETACCESSKEY=
LOG_LEVEL=debug
````

It populates the db with all the locations etc and then dies after with
```
[ DEBUG ] Server starting on http://:::8080 (Vapor/HTTPServer.swift:330)
[ WARNING ] NIOCore.SocketAddressError.unknown(host: "::", port: 8080) (Vapor/Application.swift:197)
```
